"""Render the Report JSON to a self-contained HTML document.

The template computes nothing. Every number, every ordering and every verdict
in the output was decided by the analysis layer and is read straight out of
``report.json`` — which is what makes the "same skeleton, only the data
changes" promise checkable rather than aspirational.

Two things are deliberate here:

* **Autoescape is on.** ``report.json`` carries prose written by a model that
  read untrusted retrieved context, user problem text and URLs from the page
  under test. Rendering is where that text first becomes markup, so it is the
  boundary that has to escape it.
* **Chart SVG is the single ``|safe`` exception**, and it is generated by
  ``report.charts`` from numbers — never by the model.

The stylesheet is inlined rather than linked so the document is one file with
no asset paths for Chromium to resolve at print time.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Dict

from jinja2 import Environment, FileSystemLoader, select_autoescape

from analysis.reportmodel import Report
from report import charts

TEMPLATE_DIR = Path(__file__).parent / "template"
HTML_TEMPLATE = "report.html.j2"
STYLESHEET = "style.css"


def _env() -> Environment:
    """Jinja environment with escaping on and whitespace kept predictable."""
    return Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        autoescape=select_autoescape(
            enabled_extensions=("html", "j2"), default_for_string=True, default=True
        ),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )


def build_charts(report: Report) -> Dict[str, Any]:
    """Render every chart the document needs, keyed for template lookup."""
    thresholds = report.methodology.thresholds
    pages: Dict[str, Dict[str, str]] = {}
    for page in report.pages:
        # PageBlock.metrics is a plain dict (the Run's metrics dumped whole),
        # so the cwp block is pulled out here rather than in the template -
        # the template does not reach into structures.
        cwp = page.metrics.get("cwp", {}) if isinstance(page.metrics, dict) else {}
        pages[page.name] = {
            "gauges": charts.cwv_gauges(cwp, thresholds),
            "resources": charts.resource_bars(
                [r.model_dump() for r in page.resources]
            ),
            "donut": charts.request_type_donut(page.resource_type_totals),
            "lcp": charts.lcp_phases(cwp),
            "projections": charts.projection_bars(
                {k: v.model_dump() for k, v in page.projections.items()}
            ),
        }
    return {
        "pages": pages,
        "comparison": charts.comparison_heat(
            [row.model_dump() for row in report.comparison]
        ),
    }


def render_html(report: Report) -> str:
    """Render the report to a single self-contained HTML document."""
    stylesheet = (TEMPLATE_DIR / STYLESHEET).read_text(encoding="utf-8")
    template = _env().get_template(HTML_TEMPLATE)
    return template.render(
        report=report,
        charts=build_charts(report),
        stylesheet=stylesheet,
    )
