"""Render the Report JSON to a self-contained HTML document.

The template computes nothing. Every number, every ordering and every verdict
in the output was decided by the analysis layer and is read straight out of
``report.json`` — which is what makes the "same skeleton, only the data
changes" promise checkable rather than aspirational.

Two things are deliberate here:

* **Autoescape is on.** ``report.json`` carries prose written by a model that
  read untrusted retrieved context, user problem text and URLs from the page
  under test. Rendering is where that text first becomes markup, so it is the
  boundary that has to escape it.
* **Chart SVG is the single ``|safe`` exception**, and it is generated by
  ``report.charts`` from numbers — never by the model.

The stylesheet is inlined rather than linked so the document is one file with
no asset paths for Chromium to resolve at print time.
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, Mapping, Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape

from analysis.reportmodel import Report
from report import charts
from report.images import entry_key

if TYPE_CHECKING:
    from report.images import EmbeddedImage

TEMPLATE_DIR = Path(__file__).parent / "template"
HTML_TEMPLATE = "report.html.j2"
STYLESHEET = "style.css"


def metric_label(metric: str) -> str:
    """`lcp_ms` → `LCP`. Naming, not computing — the template's own job.

    Shared with the chart builders so a trend caption and the axis of the
    chart beneath it can never disagree about what the metric is called.
    """
    return charts.METRIC_LABELS.get(str(metric), str(metric))


def transfer_size(value: Optional[float]) -> str:
    """Bytes as a short human string. Naming, not computing.

    A value the capture does not carry prints `—`, never `0`: a request with no
    recorded size is not a free request.
    """
    if value is None:
        return "—"
    size = float(value)
    for unit, scale in (("MB", 1024 * 1024), ("kB", 1024)):
        if size >= scale:
            return f"{size / scale:.1f} {unit}"
    return f"{int(size)} B"


def _env() -> Environment:
    """Jinja environment with escaping on and whitespace kept predictable."""
    env = Environment(
        loader=FileSystemLoader(str(TEMPLATE_DIR)),
        autoescape=select_autoescape(
            enabled_extensions=("html", "j2"), default_for_string=True, default=True
        ),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    env.filters["metric_label"] = metric_label
    env.filters["transfer_size"] = transfer_size
    env.filters["entry_key"] = entry_key
    return env


def build_charts(report: Report) -> Dict[str, Any]:
    """Render every chart the document needs, keyed for template lookup."""
    thresholds = report.methodology.thresholds
    pages: Dict[str, Dict[str, str]] = {}
    for page in report.pages:
        # PageBlock.metrics is a plain dict (the Run's metrics dumped whole),
        # so the cwp block is pulled out here rather than in the template -
        # the template does not reach into structures.
        cwp = page.metrics.get("cwp", {}) if isinstance(page.metrics, dict) else {}
        pages[page.name] = {
            "gauges": charts.cwv_gauges(cwp, thresholds),
            "resources": charts.resource_bars(
                [r.model_dump() for r in page.resources]
            ),
            "donut": charts.request_type_donut(page.resource_type_totals),
            "lcp": charts.lcp_phases(cwp),
            "projections": charts.projection_bars(
                {k: v.model_dump() for k, v in page.projections.items()}
            ),
            # A list, index-aligned with page.trends: both are built from the
            # same ordered sequence, so the template can pair them with
            # loop.index0 without constructing a lookup key itself.
            "trends": [
                charts.trend_chart(series.model_dump()) for series in page.trends
            ],
        }
    return {
        "pages": pages,
        "comparison": charts.comparison_heat(
            [row.model_dump() for row in report.comparison]
        ),
    }


def glance_by_page(report) -> Dict[str, list]:
    """At-a-glance rows keyed by page name, computed once per render.

    Jinja is deliberately kept free of arithmetic: the same rows have to appear
    in the Markdown mirror, and two templates computing them separately is how
    the two documents drift apart.
    """
    from config.load import Thresholds, load_settings
    from report.glossary import glance_rows, load_glossary

    glossary = load_glossary()
    try:
        thresholds = load_settings().thresholds
    except Exception:
        # Rendering must not depend on config being readable: the report layer
        # already degrades an unreadable settings file to path-only appendix
        # rows rather than losing the document. Defaults keep the targets
        # column honest — they are the same numbers the shipped file carries.
        thresholds = Thresholds()
    return {
        page.name: glance_rows(page, glossary, thresholds)
        for page in report.pages
    }


def render_html(
    report: Report, *, images: Optional[Mapping[str, "EmbeddedImage"]] = None
) -> str:
    """Render the report to a single self-contained HTML document.

    ``images`` maps an appendix entry's :func:`report.images.entry_key` to its
    embedded screenshot. It is built by the caller because embedding reads
    files, and this module is the one place the document is assembled —
    keeping the I/O outside it means a render is reproducible from its
    arguments alone. Omitting it renders the appendix with path-only rows,
    which is exactly what ``--no-appendix-images`` wants.
    """
    stylesheet = (TEMPLATE_DIR / STYLESHEET).read_text(encoding="utf-8")
    template = _env().get_template(HTML_TEMPLATE)
    return template.render(
        report=report,
        charts=build_charts(report),
        images=images or {},
        stylesheet=stylesheet,
        glance=glance_by_page(report),
    )
